In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings(action='ignore')

#-------------------- 차트 관련 속성 (한글처리, 그리드) -----------
#plt.rc('font', family='NanumGothicOTF') # For MacOS
plt.rcParams['font.family']= 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False
sns.set()

#-------------------- 주피터 , 출력결과 넓이 늘리기 ---------------
from IPython.core.display import display, HTML
display(HTML("<style>.container{width:100% !important;}</style>"))
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
pd.set_option('max_colwidth', None)

In [3]:
코스피A리스트 = pd.read_csv('/content/drive/MyDrive/컨트롤엔터산악회/코스피A리스트.csv')

In [4]:
코스피A리스트

        code  company
0    A095570   AJ네트웍스
1    A006840    AK홀딩스
2    A027410      BGF
3    A282330   BGF리테일
4    A138930  BNK금융지주
..       ...      ...
808  A005870      휴니드
809  A079980      휴비스
810  A005010      휴스틸
811  A000540     흥국화재
812  A003280     흥아해운

[813 rows x 2 columns]

In [ ]:
# A138040,A008560,A000060,A088260

In [22]:
리츠리스트 = 코스피A리스트[코스피A리스트['company'].str.contains('리츠')]['code'].tolist()

In [23]:
리츠리스트= ['A365550',
 'A400760',
 'A338100',
 'A395400',
 'A377190',
 'A330590',
 'A204210',
 'A396690',
 'A357250',
 'A404990',
 'A293940',
 'A140910',
 'A350520',
 'A334890',
 'A348950',
 'A145270',
 'A417310',
 'A357120']

In [24]:
def 리츠종목버리기(코스피A리스트):
        
    for 리츠 in 리츠리스트:
        
        행 = 코스피A리스트[코스피A리스트['code'] == 리츠].index.tolist()
        코스피A리스트 = 코스피A리스트.drop(행,axis=0)
    return 코스피A리스트

In [25]:
리츠종목버리기(코스피A리스트)

        code  company
0    A095570   AJ네트웍스
1    A006840    AK홀딩스
2    A027410      BGF
3    A282330   BGF리테일
4    A138930  BNK금융지주
..       ...      ...
808  A005870      휴니드
809  A079980      휴비스
810  A005010      휴스틸
811  A000540     흥국화재
812  A003280     흥아해운

[795 rows x 2 columns]

In [26]:
코스피A리스트[코스피A리스트['code']=='A334890'] # 잘지워진것 확인

        code  company
544  A334890  이지스밸류리츠

In [27]:
코스피최종리스트 = 코스피A리스트['code'].tolist()

In [18]:
코스피최종리스트[:3]

['A095570', 'A006840', 'A027410']

## FNSPACE 2003년 부터 호출 가능

In [ ]:
# https://www.fnspace.com/Api/FinanceApi?key=5A2CB417DA795E28F5E0&format=json&code=A005930&item=M382100,M431800,M382500,M362000,M383300,M382900,M123955&consolgb=M&annualgb=A&fraccyear=2002&toaccyear=2021

In [19]:
# dd = {"key":"5A2CB417DA795E28F5E0","format":"json","success":"true","errcd":"","errmsg":"","code":"A005930","item":"M382100,M431800,M382500,M362000,M383300,M382900,M123955","consolgb":"M","annualgb":"A","fraccyear":"2005","toaccyear":"2021","dataset":[{"CODE":"A005930","NAME":"삼성전자","DATA":[{"DATE":"2005  ","YYMM":"200512","FS_YEAR":2005,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"개별/별도","M382100":14.67465,"M431800":0.834598,"M382500":2.51382,"M362000":-28.662,"M383300":1.9513,"M382900":8.76575,"M123955":20060220},{"DATE":"2006  ","YYMM":"200612","FS_YEAR":2006,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"개별/별도","M382100":13.17395,"M431800":0.897227,"M382500":2.02101,"M362000":3.616,"M383300":1.76845,"M382900":8.10085,"M123955":20070331},{"DATE":"2007  ","YYMM":"200712","FS_YEAR":2007,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"개별/별도","M382100":12.7399,"M431800":1.438849,"M382500":1.57741,"M362000":-6.208,"M383300":1.4973,"M382900":7.13145,"M123955":20080320},{"DATE":"2008  ","YYMM":"200812","FS_YEAR":2008,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"개별/별도","M382100":13.8855,"M431800":1.219512,"M382500":1.13996,"M362000":-25.577,"M383300":1.05175,"M382900":7.216,"M123955":20090305},{"DATE":"2009  ","YYMM":"200912","FS_YEAR":2009,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"개별/별도","M382100":14.0874,"M431800":1.001252,"M382500":1.77108,"M362000":74.623,"M383300":1.5142,"M382900":10.7273,"M123955":20100311},{"DATE":"2010  ","YYMM":"201012","FS_YEAR":2010,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"연결","M382100":10.21935,"M431800":1.053741,"M382500":1.65979,"M362000":63.729,"M383300":1.04415,"M382900":6.77625,"M123955":20110310},{"DATE":"2011  ","YYMM":"201112","FS_YEAR":2011,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"연결","M382100":13.4503,"M431800":0.519849,"M382500":1.63718,"M362000":-15.294,"M383300":1.0909,"M382900":7.85415,"M123955":20120308},{"DATE":"2012  ","YYMM":"201212","FS_YEAR":2012,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"연결","M382100":11.16835,"M431800":0.525624,"M382500":1.95883,"M362000":73.25,"M383300":1.2876,"M382900":6.81915,"M123955":20130307},{"DATE":"2013  ","YYMM":"201312","FS_YEAR":2013,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"연결","M382100":7.8274,"M431800":1.042274,"M382500":1.43209,"M362000":28.621,"M383300":1.0207,"M382900":4.99755,"M123955":20140306},{"DATE":"2014  ","YYMM":"201412","FS_YEAR":2014,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"연결","M382100":9.78085,"M431800":1.507159,"M382500":1.22507,"M362000":-22.597,"M383300":1.09485,"M382900":6.10585,"M123955":20150305},{"DATE":"2015  ","YYMM":"201512","FS_YEAR":2015,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"연결","M382100":11.4668,"M431800":1.666667,"M382500":1.06263,"M362000":-19.009,"M383300":1.06835,"M382900":5.3509,"M123955":20160226},{"DATE":"2016  ","YYMM":"201612","FS_YEAR":2016,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"연결","M382100":13.1763,"M431800":1.581576,"M382500":1.35308,"M362000":24.46,"M383300":1.4631,"M382900":6.23305,"M123955":20170228},{"DATE":"2017  ","YYMM":"201712","FS_YEAR":2017,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"연결","M382100":9.4001,"M431800":1.667975,"M382500":1.67483,"M362000":98.202,"M383300":1.6222,"M382900":6.2521,"M123955":20180228},{"DATE":"2018  ","YYMM":"201812","FS_YEAR":2018,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"연결","M382100":6.42413,"M431800":3.658915,"M382500":1.095,"M362000":11.122,"M383300":1.15666,"M382900":4.20637,"M123955":20190228},{"DATE":"2019  ","YYMM":"201912","FS_YEAR":2019,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"연결","M382100":17.6252,"M431800":2.537634,"M382500":1.48689,"M362000":-47.446,"M383300":1.64509,"M382900":8.35184,"M123955":20200224},{"DATE":"2020  ","YYMM":"202012","FS_YEAR":2020,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"연결","M382100":21.08809,"M431800":3.696296,"M382500":2.05554,"M362000":21.324,"M383300":2.32344,"M382900":8.4275,"M123955":20210218},{"DATE":"2021  ","YYMM":"202112","FS_YEAR":2021,"FS_MONTH":12,"FS_QTR":"Annual","MAIN_TERM":"연결","M382100":13.55287,"M431800":1.844189,"M382500":1.7954,"M362000":50.412,"M383300":1.90221,"M382900":8.1693,"M123955":20220217}]}]}

In [ ]:
dsf_data = dd
df=pd.DataFrame(dsf_data['dataset'])
df2=pd.DataFrame(df['DATA'][0])
df2.columns=['DATE', 'YYMM', 'FS_YEAR','FS_MONTH', 'FS_QTR', 'MAIN_TERM', 'per', '현금배당수익률', 'pbr', 'esp증가율', 'psr', 'pcr', '실적보고발표일']
df2['code'] = dsf_data['code']
df2

,DATE,YYMM,FS_YEAR,FS_MONTH,FS_QTR,MAIN_TERM,per,현금배당수익률,pbr,esp증가율,psr,pcr,실적보고발표일,code
0,2005,200512,2005,12,Annual,개별/별도,14.67465,0.834598,2.51382,-28.662,1.95130,8.76575,20060220,A005930
1,2006,200612,2006,12,Annual,개별/별도,13.17395,0.897227,2.02101,3.616,1.76845,8.10085,20070331,A005930
2,2007,200712,2007,12,Annual,개별/별도,12.73990,1.438849,1.57741,-6.208,1.49730,7.13145,20080320,A005930
3,2008,200812,2008,12,Annual,개별/별도,13.88550,1.219512,1.13996,-25.577,1.05175,7.21600,20090305,A005930
4,2009,200912,2009,12,Annual,개별/별도,14.08740,1.001252,1.77108,74.623,1.51420,10.72730,20100311,A005930
5,2010,201012,2010,12,Annual,연결,10.21935,1.053741,1.65979,63.729,1.04415,6.77625,20110310,A005930
6,2011,201112,2011,12,Annual,연결,13.45030,0.519849,1.63718,-15.294,1.09090,7.85415,20120308,A005930
7,2012,201212,2012,12,Annual,연결,11.16835,0.525624,1.95883,73.250,1.28760,6.81915,20130307,A005930
8,2013,201312,2013,12,Annual,연결,7.82740,1.042274,1.43209,28.621,1.02070,4.99755,20140306,A005930
9,2014,201412,2014,12,Annual,연결,9.78085,1.507159,1.22507,-22.597,1.09485,6.10585,20150305,A005930
10,2015,201512,2015,12,Annual,연결,11.46680,1.666667,1.06263,-19.009,1.06835,5.35090,20160226,A005930
11,2016,201612,2016,12,Annual,연결,13.17630,1.581576,1.35308,24.460,1.46310,6.23305,20170228,A005930
12,2017,201712,2017,12,Annual,연결,9.40010,1.667975,1.67483,98.202,1.62220,6.25210,20180228,A005930
13,2018,201812,2018,12,Annual,연결,6.42413,3.658915,1.09500,11.122,1.15666,4.20637,20190228,A005930
14,2019,201912,2019,12,Annual,연결,17.62520,2.537634,1.48689,-47.446,1.64509,8.35184,20200224,A005930
15,2020,202012,2020,12,Annual,연결,21.08809,3.696296,2.05554,21.324,2.32344,8.42750,20210218,A005930
16,2021,202112,2021,12,Annual,연결,13.55287,1.844189,1.79540,50.412,1.90221,8.16930,20220217,A005930

In [ ]:
코스피3개 = 코스피최종리스트[:3]

In [ ]:
def call_api(코스피3개):

    
    for stockcode in 코스피3개:
            
        dsf_data = pd.read_json("https://www.fnspace.com/Api/FinanceApi?key=5A2CB417DA795E28F5E0&format=json&code="+stockcode+"&item=M382100,M431800,M382500,M362000,M383300,M382900,M123955&consolgb=M&annualgb=A&fraccyear=2003&toaccyear=2021",typ='series')
        df=pd.DataFrame(dsf_data['dataset'])
        df2=pd.DataFrame(df['DATA'][0])
        df2.columns=['DATE', 'YYMM', 'FS_YEAR','FS_MONTH', 'FS_QTR', 'MAIN_TERM', 'per', '현금배당수익률', 'pbr', 'esp증가율', 'psr', 'pcr', '실적보고발표일']
        df2['code'] = dsf_data['code']

        코스피재무제표 = pd.concat([코스피재무제표, df2])
    return 코스피재무제표

In [30]:
코스피재무제표 = pd.DataFrame()

In [31]:
len(코스피최종리스트)

813

In [32]:
for stockcode in 코스피최종리스트:
        
    dsf_data = pd.read_json("https://www.fnspace.com/Api/FinanceApi?key=5A2CB417DA795E28F5E0&format=json&code="+stockcode+"&item=M223000,M241000,M122700&consolgb=M&annualgb=A&fraccyear=2003&toaccyear=2021",typ='series')
    df=pd.DataFrame(dsf_data['dataset'])
    df2=pd.DataFrame(df['DATA'][0])
    df2.columns=['DATE', 'YYMM', 'FS_YEAR','FS_MONTH', 'FS_QTR', 'MAIN_TERM', '자본유보율','총자산회전율','당기순이익']
    df2['code'] = dsf_data['code']

    코스피재무제표 = pd.concat([코스피재무제표, df2])

In [33]:
코스피재무제표.to_csv('코스피추가옵션.csv',index=True)

In [34]:
코스피재무제표

,DATE,YYMM,FS_YEAR,FS_MONTH,FS_QTR,MAIN_TERM,자본유보율,총자산회전율,당기순이익,code
0,2003,200312,2003,12,Annual,개별/별도,21.046,0.75988,1228127.0,A095570
1,2004,200412,2004,12,Annual,개별/별도,39.159,0.75058,1761727.0,A095570
2,2005,200512,2005,12,Annual,개별/별도,59.356,0.76187,2334892.0,A095570
3,2006,200612,2006,12,Annual,개별/별도,90.183,0.65345,3105783.0,A095570
4,2007,200712,2007,12,Annual,개별/별도,142.073,0.67337,3627809.0,A095570
...,...,...,...,...,...,...,...,...,...,...
14,2017,201712,2017,12,Annual,연결,151.638,0.91316,-61991930.17,A003280
15,2018,201812,2018,12,Annual,연결,13.003,0.12023,-86540155.6,A003280
16,2019,201912,2019,12,Annual,연결,12.978,0.1655,-51356550.72,A003280
17,2020,202012,2020,12,Annual,연결,-74.754,0.24783,-50876456.21,A003280
18,2021,202112,2021,12,Annual,연결,13.693,0.30604,16436494.24,A003280

In [ ]:
코스피추가재무제표 = pd.read_csv('/content/코스피추가재무제표.csv')

In [ ]:
코스피추가재무제표['code'].nunique()

795

# 추가로 불러오기

In [20]:
코스피재무제표 = pd.DataFrame()

In [21]:
len(코스피최종리스트)

813

In [ ]:
for stockcode in 코스피최종리스트:
        
    dsf_data = pd.read_json("https://www.fnspace.com/Api/FinanceApi?key=5A2CB417DA795E28F5E0&format=json&code="+stockcode+"&item=M382100,M431800,M382500,M362000,M383300,M382900,M123955&consolgb=M&annualgb=A&fraccyear=2003&toaccyear=2021",typ='series')
    df=pd.DataFrame(dsf_data['dataset'])
    df2=pd.DataFrame(df['DATA'][0])
    df2.columns=['DATE', 'YYMM', 'FS_YEAR','FS_MONTH', 'FS_QTR', 'MAIN_TERM', 'per', '현금배당수익률', 'pbr', 'esp증가율', 'psr', 'pcr', '실적보고발표일']
    df2['code'] = dsf_data['code']

    코스피재무제표 = pd.concat([코스피재무제표, df2])

In [ ]:
코스피재무제표.to_csv('코스피추가재무제표.csv',index=True)

In [ ]:
코스피추가재무제표 = pd.read_csv('/content/코스피추가재무제표.csv')

In [ ]:
코스피추가재무제표['code'].nunique()

795