In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings(action='ignore')

#-------------------- 차트 관련 속성 (한글처리, 그리드) -----------
#plt.rc('font', family='NanumGothicOTF') # For MacOS
plt.rcParams['font.family']= 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False
sns.set()

#-------------------- 주피터 , 출력결과 넓이 늘리기 ---------------
from IPython.core.display import display, HTML
display(HTML("<style>.container{width:100% !important;}</style>"))
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
pd.set_option('max_colwidth', None)

In [84]:
코스피 = pd.read_csv('/content/drive/MyDrive/컨트롤엔터산악회/주식포트폴리오/코스피상장종목.csv', encoding='cp949')

코스닥 = pd.read_csv('/content/drive/MyDrive/컨트롤엔터산악회/주식포트폴리오/코스닥상장종목.csv', encoding='cp949')

In [85]:
print(코스피.info())
코스피.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 820 entries, 0 to 819
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목코드    820 non-null    int64
 1   종목명     820 non-null    object
 2   시장구분    820 non-null    object
 3   소속부     0 non-null      float64
 4   소속부.1   0 non-null      float64
 5   업종코드    820 non-null    int64
 6   업종명     820 non-null    object
 7   결산월     820 non-null    int64
 8   지정자문인   0 non-null      float64
 9   상장주식수   820 non-null    int64
 10  액면가     820 non-null    object
 11  자본금     820 non-null    int64
 12  통화구분    818 non-null    object
 13  대표이사    820 non-null    object
 14  대표전화    812 non-null    object
 15  주소      820 non-null    object
dtypes: float64(3), int64(5), object(8)
memory usage: 102.6+ KB
None

,종목코드,종목명,시장구분,소속부,소속부.1,업종코드,업종명,결산월,지정자문인,상장주식수,액면가,자본금,통화구분,대표이사,대표전화,주소
0,95570,AJ네트웍스,KOSPI,NaN,NaN,147603,산업용 기계 및 장비 임대업,12,NaN,46822295,1000,46822295000,원(KRW),"박대현, 손삼달",02-6363-9999,"서울특별시 송파구 정의로8길 9 (문정동,AJ빌딩)"
1,6840,AK홀딩스,KOSPI,NaN,NaN,116409,기타 금융업,12,NaN,13247561,5000,66237805000,원(KRW),"채형석, 이석주(각자 대표이사)",02-768-2923,서울특별시 마포구 양화로 188 -
2,27410,BGF,KOSPI,NaN,NaN,116409,기타 금융업,12,NaN,95716791,1000,95716791000,NaN,홍정국,1577-3663,서울특별시 강남구 테헤란로 405
3,282330,BGF리테일,KOSPI,NaN,NaN,74701,종합 소매업,12,NaN,17283906,1000,17283906000,원(KRW),이건준,02-1577-8007,서울특별시 강남구 테헤란로 405 BGF사옥
4,138930,BNK금융지주,KOSPI,NaN,NaN,116409,기타 금융업,12,NaN,325935246,5000,1629676230000,원(KRW),김지완,051-620-3023,부산광역시 남구 문현금융로 30(문현동)

In [86]:
코스피 = 코스피[['종목코드','종목명','시장구분','업종코드','업종명','상장주식수','액면가','자본금']]
코스피.head()

,종목코드,종목명,시장구분,업종코드,업종명,상장주식수,액면가,자본금
0,95570,AJ네트웍스,KOSPI,147603,산업용 기계 및 장비 임대업,46822295,1000,46822295000
1,6840,AK홀딩스,KOSPI,116409,기타 금융업,13247561,5000,66237805000
2,27410,BGF,KOSPI,116409,기타 금융업,95716791,1000,95716791000
3,282330,BGF리테일,KOSPI,74701,종합 소매업,17283906,1000,17283906000
4,138930,BNK금융지주,KOSPI,116409,기타 금융업,325935246,5000,1629676230000

In [87]:
코스피.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 820 entries, 0 to 819
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목코드    820 non-null    int64
 1   종목명     820 non-null    object
 2   시장구분    820 non-null    object
 3   업종코드    820 non-null    int64
 4   업종명     820 non-null    object
 5   상장주식수   820 non-null    int64
 6   액면가     820 non-null    object
 7   자본금     820 non-null    int64
dtypes: int64(4), object(4)
memory usage: 51.4+ KB

In [88]:
코스피['업종명'].unique()

array(['산업용 기계 및 장비 임대업', '기타 금융업', '종합 소매업', '봉제의복 제조업',
       '영화, 비디오물, 방송프로그램 제작 및 배급업', '도로 화물 운송업', '기타 식품 제조업',
       '컴퓨터 프로그래밍, 시스템 통합 및 관리업', '금융 지원 서비스업', '보험업', '반도체 제조업',
       '상품 중개업', '건물 건설업', '토목 건설업', '고무제품 제조업', '1차 비철금속 제조업',
       '1차 철강 제조업', '기타 전문 도매업', '부동산 임대 및 공급업', '유원지 및 기타 오락관련 서비스업',
       '상품 종합 도매업', '전기 및 통신 공사업', '기타 화학제품 제조업', '석유 정제품 제조업',
       '기타 비금속광물 광업', '해상 운송업', '일반 목적용 기계 제조업', '의약품 제조업',
       '유리 및 유리제품 제조업', '기초 화학물질 제조업', '전자부품 제조업', '그외 기타 운송장비 제조업',
       '전기 통신업', '담배 제조업', '기타 정보 서비스업', '일차전지 및 축전지 제조업',
       '통신 및 방송 장비 제조업', '텔레비전 방송업', '무기 및 총포탄 제조업',
       '전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업', '플라스틱제품 제조업', '알코올음료 제조업',
       '자료처리, 호스팅, 포털 및 기타 인터넷 정보매개 서비스업', '소프트웨어 개발 및 공급업',
       '회사 본부 및 경영 컨설팅 서비스업', '전기업', '자동차 신품 부품 제조업', '특수 목적용 기계 제조업',
       '자동차 부품 및 내장품 판매업', '운송장비 임대업', '기초 의약물질 및 생물학적 제제 제조업',
       '자연과학 및 공학 연구개발업', '합성고무 및 플라스틱 물질 제조업', '나무제품 제조업',
       '절연선 및 케이블 제조업', '스포츠 서비스업', '비료, 농약 및 살균, 살충제 제조업', '가정용 기기 제조업',
       '연료용 가스 제조 및 배관공급업', '곡물가공품, 전분 및 전분제품 제조업', '음·식료품 및 담배 도매업',
       '생활용품 도매업', '전구 및 조명장치 제조업', '자동차용 엔진 및 자동차 제조업', '은행 및 저축기관',
       '펄프, 종이 및 판지 제조업', '낙농제품 및 식용빙과류 제조업', '구조용 금속제품, 탱크 및 증기발생기 제조업',
       '초등 교육기관', '내화, 비내화 요업제품 제조업', '기타 금속 가공제품 제조업', '연료 소매업',
       '골판지, 종이 상자 및 종이용기 제조업', '선박 및 보트 건조업', '직물직조 및 직물제품 제조업',
       '항공 여객 운송업', '화학섬유 제조업', '의료용 기기 제조업', '건축기술, 엔지니어링 및 관련 기술 서비스업',
       '기타 운송관련 서비스업', '기반조성 및 시설물 축조관련 전문공사업',
       '시멘트, 석회, 플라스터 및 그 제품 제조업', '육상 여객 운송업', '어로 어업',
       '측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외', '여행사 및 기타 여행보조 서비스업',
       '비알코올음료 및 얼음 제조업', '가전제품 및 정보통신장비 소매업', '도축, 육류 가공 및 저장 처리업',
       '신탁업 및 집합투자업', '기타 종이 및 판지 제품 제조업', '기타 비금속 광물제품 제조업',
       '서적, 잡지 및 기타 인쇄물 출판업', '수산물 가공 및 저장 처리업', '가죽, 가방 및 유사제품 제조업',
       '악기 제조업', '영상 및 음향기기 제조업', '금속 주조업', '동물용 사료 및 조제식품 제조업', '가구 제조업',
       '컴퓨터 및 주변장치 제조업', '섬유, 의복, 신발 및 가죽제품 소매업', '음식점업',
       '산업용 농·축산물 및 동·식물 도매업', '기계장비 및 관련 물품 도매업', '기타 사업지원 서비스업',
       '그외 기타 제품 제조업', '경비, 경호 및 탐정업', '보험 및 연금관련 서비스업', '자동차 판매업',
       '일반 및 생활 숙박시설 운영업', '건물설비 설치 공사업', '광고업', '귀금속 및 장신용품 제조업',
       '방적 및 가공사 제조업', '건축자재, 철물 및 난방장치 도매업', '편조원단 제조업',
       '증기, 냉·온수 및 공기조절 공급업', '재 보험업', '그외 기타 개인 서비스업', '개인 및 가정용품 임대업',
       '기타 전기장비 제조업', '오디오물 출판 및 원판 녹음업', '항공기,우주선 및 부품 제조업',
       '제재 및 목재 가공업', '철도장비 제조업', '무점포 소매업', '기타 상품 전문 소매업',
       '신발 및 신발 부분품 제조업'], dtype=object)

In [89]:
코스피제거인덱스 = 코스피[코스피['종목명'].str.contains('스팩')].index.tolist()

In [90]:
코스피 = 코스피.drop(코스피제거인덱스,axis=0)

In [91]:
print(코스피.info())
코스피.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 819 entries, 0 to 819
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목코드    819 non-null    int64
 1   종목명     819 non-null    object
 2   시장구분    819 non-null    object
 3   업종코드    819 non-null    int64
 4   업종명     819 non-null    object
 5   상장주식수   819 non-null    int64
 6   액면가     819 non-null    object
 7   자본금     819 non-null    int64
dtypes: int64(4), object(4)
memory usage: 57.6+ KB
None

,종목코드,종목명,시장구분,업종코드,업종명,상장주식수,액면가,자본금
0,95570,AJ네트웍스,KOSPI,147603,산업용 기계 및 장비 임대업,46822295,1000,46822295000
1,6840,AK홀딩스,KOSPI,116409,기타 금융업,13247561,5000,66237805000
2,27410,BGF,KOSPI,116409,기타 금융업,95716791,1000,95716791000
3,282330,BGF리테일,KOSPI,74701,종합 소매업,17283906,1000,17283906000
4,138930,BNK금융지주,KOSPI,116409,기타 금융업,325935246,5000,1629676230000

In [92]:
코스피[코스피['종목명'].str.contains('호')]

,종목코드,종목명,시장구분,업종코드,업종명,상장주식수,액면가,자본금
170,2990,금호건설,KOSPI,64101,건물 건설업,36633924,5000,184630950000
171,11780,금호석유,KOSPI,32001,기초 화학물질 제조업,30295844,5000,167455885000
172,214330,금호에이치티,KOSPI,33003,자동차 신품 부품 제조업,196590027,500,98295013500
173,1210,금호전기,KOSPI,32804,전구 및 조명장치 제조업,20861019,500,10430509500
174,73240,금호타이어,KOSPI,32201,고무제품 제조업,287260287,5000,1436301435000
237,69460,대호에이엘,KOSPI,32402,1차 비철금속 제조업,52003519,500,26001759500
299,1080,만호제강,KOSPI,32401,1차 철강 제조업,4150000,1000,4150000000
327,155900,바다로19호,KOSPI,147601,운송장비 임대업,15200004,5000,76000020000
384,10960,삼호개발,KOSPI,64201,기반조성 및 시설물 축조관련 전문공사업,25000000,500,12500000000
794,111110,호전실업,KOSPI,31401,봉제의복 제조업,9685882,500,5500821000
795,8770,호텔신라,KOSPI,74708,기타 상품 전문 소매업,39248121,5000,200000000000

In [93]:
  코스피['종목코드'] = 코스피['종목코드'].astype(str)

In [94]:
코스피['종목코드']

0       95570
1        6840
2       27410
3      282330
4      138930
        ...
815      5870
816     79980
817      5010
818       540
819      3280
Name: 종목코드, Length: 819, dtype: object

In [95]:
 코스피['종목코드'] =  코스피['종목코드'].str.zfill(6)

# 관리종목대상 코스피 기준 제거해야한다.
1. 007610 선도전기
2. 012600 센트럴인사이트
3. 003620 쌍용차
4. 015540 쎌마테라퓨틱스
5. 008500 일정실업
6. 019490 하이트론

In [96]:
관리종목 = pd.read_csv('/content/drive/MyDrive/컨트롤엔터산악회/주식포트폴리오/코스피관리종목추리기.csv', encoding='cp949')

In [97]:
관리종목 = 관리종목[관리종목['관리종목'] != 'X']

In [100]:
관리종목 = 관리종목[['종목코드','종목명','관리종목']]

In [101]:
코스피 = pd.merge(코스피,관리종목, how='outer', on='종목명')

In [102]:
코스피

,종목코드_x,종목명,시장구분,업종코드,업종명,상장주식수,액면가,자본금,종목코드_y,관리종목
0,095570,AJ네트웍스,KOSPI,147603,산업용 기계 및 장비 임대업,46822295,1000,46822295000,NaN,NaN
1,006840,AK홀딩스,KOSPI,116409,기타 금융업,13247561,5000,66237805000,NaN,NaN
2,027410,BGF,KOSPI,116409,기타 금융업,95716791,1000,95716791000,NaN,NaN
3,282330,BGF리테일,KOSPI,74701,종합 소매업,17283906,1000,17283906000,NaN,NaN
4,138930,BNK금융지주,KOSPI,116409,기타 금융업,325935246,5000,1629676230000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
814,005870,휴니드,KOSPI,32604,통신 및 방송 장비 제조업,14116015,5000,70580075000,NaN,NaN
815,079980,휴비스,KOSPI,32005,화학섬유 제조업,34500000,5000,172500000000,NaN,NaN
816,005010,휴스틸,KOSPI,32401,1차 철강 제조업,7837615,5000,39188075000,NaN,NaN
817,000540,흥국화재,KOSPI,116501,보험업,64242645,5000,325821225000,NaN,NaN
818,003280,흥아해운,KOSPI,85001,해상 운송업,240424899,500,120212449500,NaN,NaN

In [105]:
코스피 = 코스피[코스피['관리종목'].isna()==True]

In [109]:
코스피 = 코스피.drop(['종목코드_y','관리종목'],axis=1)

In [112]:
코스피.columns = ['종목코드', '종목명', '시장구분', '업종코드', '업종명', '상장주식수', '액면가', '자본금']

In [114]:
코스피.to_csv('코스피종목리스트',index=False)

In [115]:
코스피종목 = pd.read_csv('/content/drive/MyDrive/컨트롤엔터산악회/주식포트폴리오/코스피종목리스트.csv')
코스닥종목 = pd.read_csv('/content/drive/MyDrive/컨트롤엔터산악회/주식포트폴리오/코스닥종목리스트.csv')

In [116]:
코스피종목

,종목코드,종목명,시장구분,업종코드,업종명,상장주식수,액면가,자본금
0,95570,AJ네트웍스,KOSPI,147603,산업용 기계 및 장비 임대업,46822295,1000,46822295000
1,6840,AK홀딩스,KOSPI,116409,기타 금융업,13247561,5000,66237805000
2,27410,BGF,KOSPI,116409,기타 금융업,95716791,1000,95716791000
3,282330,BGF리테일,KOSPI,74701,종합 소매업,17283906,1000,17283906000
4,138930,BNK금융지주,KOSPI,116409,기타 금융업,325935246,5000,1629676230000
...,...,...,...,...,...,...,...,...
808,5870,휴니드,KOSPI,32604,통신 및 방송 장비 제조업,14116015,5000,70580075000
809,79980,휴비스,KOSPI,32005,화학섬유 제조업,34500000,5000,172500000000
810,5010,휴스틸,KOSPI,32401,1차 철강 제조업,7837615,5000,39188075000
811,540,흥국화재,KOSPI,116501,보험업,64242645,5000,325821225000
812,3280,흥아해운,KOSPI,85001,해상 운송업,240424899,500,120212449500

In [117]:
코스닥종목

,종목코드,종목명,시장구분,업종코드,업종명,상장주식수,액면가,자본금
0,60310,3S,KOSDAQ,32602.0,전자부품 제조업,46271513.0,500,2.313576e+10
1,54620,APS홀딩스,KOSDAQ,116409.0,기타 금융업,20394221.0,500,1.019711e+10
2,265520,AP시스템,KOSDAQ,32902.0,특수 목적용 기계 제조업,15281421.0,500,7.640710e+09
3,211270,AP위성,KOSDAQ,32604.0,통신 및 방송 장비 제조업,15082304.0,500,7.541152e+09
4,13720,CBI,KOSDAQ,33003.0,자동차 신품 부품 제조업,67660032.0,100,6.766003e+09
...,...,...,...,...,...,...,...,...
1395,24060,흥구석유,KOSDAQ,74607.0,기타 전문 도매업,15000000.0,100,1.500000e+09
1396,10240,흥국,KOSDAQ,32902.0,특수 목적용 기계 제조업,12322696.0,500,6.161348e+09
1397,189980,흥국에프엔비,KOSDAQ,31102.0,비알코올음료 및 얼음 제조업,39997771.0,100,3.999777e+09
1398,37440,희림,KOSDAQ,137201.0,"건축기술, 엔지니어링 및 관련 기술 서비스업",13922475.0,500,6.961238e+09
1399,238490,힘스,KOSDAQ,32902.0,특수 목적용 기계 제조업,11312236.0,500,5.656118e+09