In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings(action='ignore')

#-------------------- 차트 관련 속성 (한글처리, 그리드) -----------
#plt.rc('font', family='NanumGothicOTF') # For MacOS
plt.rcParams['font.family']= 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False
sns.set()

#-------------------- 주피터 , 출력결과 넓이 늘리기 ---------------
from IPython.core.display import display, HTML
display(HTML("<style>.container{width:100% !important;}</style>"))
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
pd.set_option('max_colwidth', None)

# 상장기업목록

In [3]:
import pandas as pd
import time


#최종 결과 데이타를 담을 DataFrame 생성
df_result = pd.DataFrame(columns=['CODE', 'DT'])
print(df_result)

def read_krx_code():
    """KRX로부터 상장기업 목록 파일을 읽어와서 FnSpace용(기업코드 앞에 'A' 추가) DataFrame으로 변경 후 반환"""
    url = 'http://kind.krx.co.kr/corpgeneral/corpList.do?method=download&searchType=13'
    krx = pd.read_html(url, header=0)[0]
    종목 = krx[['종목코드', '회사명']]
    종목 = 종목.rename(columns={'종목코드':'code', '회사명': 'company'})
    종목.code = 종목.code.map('{:06d}'.format)
    for i in range(len(종목)):
        종목['code'][i] = 'A'+종목['code'][i]
    return krx,종목
krx,종목 = read_krx_code()

Empty DataFrame
Columns: [CODE, DT]
Index: []

In [4]:
krx

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,DL,210,기타 금융업,지주회사,1976-02-02,12월,전병욱,http://www.dlholdings.co.kr,서울특별시
1,DRB동일,4840,고무제품 제조업,"고무벨트(V벨트,콘베이어벨트,평벨트),프라스틱제품 제조,판매",1976-05-21,12월,류영식,http://drbworld.com,부산광역시
2,DSR,155660,1차 비철금속 제조업,합섬섬유로프,2013-05-15,12월,홍석빈,http://www.dsr.com,부산광역시
3,GS,78930,기타 금융업,지주회사/부동산 임대,2004-08-05,12월,"허태수, 홍순기 (각자 대표이사)",NaN,서울특별시
4,KG케미칼,1390,기초 화학물질 제조업,"콘크리트혼화제, 비료, 친환경농자재, 수처리제",1989-08-25,12월,"곽정현, 김재익",http://www.kgchem.co.kr,울산광역시
...,...,...,...,...,...,...,...,...,...
2494,토마토시스템,393210,소프트웨어 개발 및 공급업,UI솔루션,2021-10-14,12월,이상돈,http://www.tomatosystem.co.kr/,서울특별시
2495,틸론,217880,소프트웨어 개발 및 공급업,"Cloud Solution (D,A,E,Rstation)",2015-05-28,12월,최백준,http://www.tilon.co.kr,서울특별시
2496,플럼라인생명과학,222670,자연과학 및 공학 연구개발업,"강아지암치료제,돼지DNA테라피",2015-07-28,12월,김앤토니경태,http://www.plsdna.com,서울특별시
2497,한국미라클피플사,331660,기타 화학제품 제조업,"은나노스텝, 닥터오렌지 등",2019-10-28,12월,이호경,http://www.kmpc.co.kr,경기도
2498,휴벡셀,212310,의료용 기기 제조업,척추용 임플란트 등,2016-07-26,12월,"박정민, 허성규(각자대표)",http://huvexel.com,경기도

In [5]:
종목

         code   company
0     A000210        DL
1     A004840     DRB동일
2     A155660       DSR
3     A078930        GS
4     A001390     KG케미칼
...       ...       ...
2494  A393210    토마토시스템
2495  A217880        틸론
2496  A222670  플럼라인생명과학
2497  A331660  한국미라클피플사
2498  A212310       휴벡셀

[2499 rows x 2 columns]

# API 호출하기

In [6]:
# ! pip install json

# 2019~2020년의 삼성전자 per api주소

In [7]:
# https://www.fnspace.com/Api/FinanceApi?key=E4585454D3DA767D3330&format=json&code=A005930&item=M382100&consolgb=M&annualgb=A&fraccyear=2019&toaccyear=2020

In [11]:
삼성전자_per = pd.read_json("https://www.fnspace.com/Api/FinanceApi?key=E4585454D3DA767D3330&format=json&code=A005930&item=M382100&consolgb=M&annualgb=A&fraccyear=2019&toaccyear=2020",typ='series') # 이거 여시면 돈나가요

In [9]:
# https://www.fnspace.com/Api/FinanceApi?key=[API아이디]&format=json&code=[코드_list]&item=[재무요소_list]&consolgb=M&annualgb=A&fraccyear=[시작년도]&toaccyear=[마지막연도]",typ='series')  # 예시로 든것입니다

In [12]:
per_2019 = 삼성전자_per['dataset'][0]['DATA'][0]
per_2020 = 삼성전자_per['dataset'][0]['DATA'][1]

In [13]:
print(per_2019['M382100'],per_2020['M382100'])

17.6252 21.08809

In [14]:
p19 = per_2019['M382100']
p20 = per_2020['M382100']

In [15]:
[p19,p20]

[17.6252, 21.08809]

In [17]:
삼성전자재무 = pd.DataFrame(삼성전자_per["dataset"])
삼성전자 = pd.DataFrame(삼성전자재무["DATA"][0])

In [20]:
삼성전자_per

key                                                                                                                                                                                                                                                                                                          E4585454D3DA767D3330
format                                                                                                                                                                                                                                                                                                                       json
success                                                                                                                                                                                                                                                                                                                      true
errcd
errmsg
code                                                                                                                                                                                                                                                                                                                      A005930
item                                                                                                                                                                                                                                                                                                                      M382100
consolgb                                                                                                                                                                                                                                                                                                                        M
annualgb                                                                                                                                                                                                                                                                                                                        A
fraccyear                                                                                                                                                                                                                                                                                                                    2019
toaccyear                                                                                                                                                                                                                                                                                                                    2020
dataset      [{'CODE': 'A005930', 'NAME': '삼성전자', 'DATA': [{'DATE': '2019  ', 'YYMM': '201912', 'FS_YEAR': 2019, 'FS_MONTH': 12, 'FS_QTR': 'Annual', 'MAIN_TERM': '연결', 'M382100': 17.6252}, {'DATE': '2020  ', 'YYMM': '202012', 'FS_YEAR': 2020, 'FS_MONTH': 12, 'FS_QTR': 'Annual', 'MAIN_TERM': '연결', 'M382100': 21.08809}]}]
dtype: object

In [18]:
삼성전자재무

,CODE,NAME,DATA
0,A005930,삼성전자,"[{'DATE': '2019 ', 'YYMM': '201912', 'FS_YEAR': 2019, 'FS_MONTH': 12, 'FS_QTR': 'Annual', 'MAIN_TERM': '연결', 'M382100': 17.6252}, {'DATE': '2020 ', 'YYMM': '202012', 'FS_YEAR': 2020, 'FS_MONTH': 12, 'FS_QTR': 'Annual', 'MAIN_TERM': '연결', 'M382100': 21.08809}]"

In [19]:
삼성전자

     DATE    YYMM  FS_YEAR  FS_MONTH  FS_QTR MAIN_TERM   M382100
0  2019    201912     2019        12  Annual        연결  17.62520
1  2020    202012     2020        12  Annual        연결  21.08809

In [ ]:
url = "https://www.fnspace.com/Api/FinanceApi?key="
def 재무재표만플기(url):
        
    재무제표API주소 = pd.read_json(url)   #2000~2021까지 가져오는 경우
    딕트타입 = pd.DataFrame(재무제표API주소["dataset"])
    원하는재무제표= pd.DataFrame(딕트타입["DATA"][0])
    
    return 원하는재무제표     #특정종목 1개기업만 데이터프레임 하는 함수

# 종목리스트 불러오기

In [21]:
코스피 = pd.read_csv('/content/drive/MyDrive/컨트롤엔터산악회/주식포트폴리오/코스피종목리스트.csv')
코스닥 = pd.read_csv('/content/drive/MyDrive/컨트롤엔터산악회/주식포트폴리오/코스닥종목리스트.csv')

In [22]:
코스피.head()

,종목코드,종목명,시장구분,업종코드,업종명,상장주식수,액면가,자본금
0,95570,AJ네트웍스,KOSPI,147603,산업용 기계 및 장비 임대업,46822295,1000,46822295000
1,6840,AK홀딩스,KOSPI,116409,기타 금융업,13247561,5000,66237805000
2,27410,BGF,KOSPI,116409,기타 금융업,95716791,1000,95716791000
3,282330,BGF리테일,KOSPI,74701,종합 소매업,17283906,1000,17283906000
4,138930,BNK금융지주,KOSPI,116409,기타 금융업,325935246,5000,1629676230000

In [36]:
코스닥

,종목코드,종목명,시장구분,업종코드,업종명,상장주식수,액면가,자본금
0,60310,3S,KOSDAQ,32602.0,전자부품 제조업,46271513.0,500,2.313576e+10
1,54620,APS홀딩스,KOSDAQ,116409.0,기타 금융업,20394221.0,500,1.019711e+10
2,265520,AP시스템,KOSDAQ,32902.0,특수 목적용 기계 제조업,15281421.0,500,7.640710e+09
3,211270,AP위성,KOSDAQ,32604.0,통신 및 방송 장비 제조업,15082304.0,500,7.541152e+09
4,13720,CBI,KOSDAQ,33003.0,자동차 신품 부품 제조업,67660032.0,100,6.766003e+09
...,...,...,...,...,...,...,...,...
1395,24060,흥구석유,KOSDAQ,74607.0,기타 전문 도매업,15000000.0,100,1.500000e+09
1396,10240,흥국,KOSDAQ,32902.0,특수 목적용 기계 제조업,12322696.0,500,6.161348e+09
1397,189980,흥국에프엔비,KOSDAQ,31102.0,비알코올음료 및 얼음 제조업,39997771.0,100,3.999777e+09
1398,37440,희림,KOSDAQ,137201.0,"건축기술, 엔지니어링 및 관련 기술 서비스업",13922475.0,500,6.961238e+09
1399,238490,힘스,KOSDAQ,32902.0,특수 목적용 기계 제조업,11312236.0,500,5.656118e+09

In [34]:
코스피리스트 = 코스피[['종목코드', '종목명']]
코스피리스트 = 코스피리스트.rename(columns={'종목코드':'code', '종목명': 'company'})
코스피리스트.code = 코스피리스트.code.map('{:06d}'.format)
for i in range(len(코스피리스트)):
    코스피리스트['code'][i] = 'A'+코스피리스트['code'][i]
코스피리스트

        code  company
0    A095570   AJ네트웍스
1    A006840    AK홀딩스
2    A027410      BGF
3    A282330   BGF리테일
4    A138930  BNK금융지주
..       ...      ...
808  A005870      휴니드
809  A079980      휴비스
810  A005010      휴스틸
811  A000540     흥국화재
812  A003280     흥아해운

[813 rows x 2 columns]

In [39]:
코스피리스트.to_csv('코스피A리스트.csv',index=False)

In [35]:
코스닥리스트 = 코스닥[['종목코드', '종목명']]
코스닥리스트 = 코스닥리스트.rename(columns={'종목코드':'code', '종목명': 'company'})
코스닥리스트.code = 코스닥리스트.code.map('{:06d}'.format)
for i in range(len(코스닥리스트)):
    코스닥리스트['code'][i] = 'A'+코스닥리스트['code'][i]
코스닥리스트

         code company
0     A060310      3S
1     A054620  APS홀딩스
2     A265520   AP시스템
3     A211270    AP위성
4     A013720     CBI
...       ...     ...
1395  A024060    흥구석유
1396  A010240      흥국
1397  A189980  흥국에프엔비
1398  A037440      희림
1399  A238490      힘스

[1400 rows x 2 columns]

In [40]:
코스닥리스트.to_csv('코스닥A리스트.csv',index=False)

# 딥서치 사이트로 일일이 다 엑셀다운로드를 받으면 분기까지 가능하다
ref : https://deepsearch.com/

#가져오고싶은 재무데이터 호출하기

In [ ]:
# KRX로부터 받은 상장기업을 기준으로 순차적 재무정보 조회
for index, corpCode in corp_data.iterrows():

    # 정보 받아오는 과정을 알 수 있도록 진행상태 + 진행 기업 출력
    print((index+1).__str__()+"/"+len(corp_data).__str__())
    print("#"+(index+1).__str__()+" "+corp_data_all['company'][index]+'데이터를 가져옵니다.\n')

    # 15년도 1분기 ~ 20년도 4분기 동안 기업 매출액, 매출원가, 판관비, 금융수익, 당기순이익
    dsf_data_state = pd.read_json(
        "http://www.fnspace.com/Api/FinanceApi?key=sample&format=json&code="+corpCode["code"]+"&item=M121000,M121100,M121300,M121540,M122700&consolgb=C&annualgb=QQ&accdategb=C&fraccyear=201503&toaccyear=202012",
        typ='series')

    if dsf_data_state["success"] == 'true':
        df_state = pd.DataFrame(dsf_data_state['dataset'])
        for index2, row in df_state.iterrows():
            df_temp = pd.DataFrame(row["DATA"])
            df_temp["CODE"] = row["CODE"]
            df_result = df_temp.append(df_result, ignore_index=True, sort=False)
        print("성공! \n")
    else:
            print(dsf_data_state["errmsg"])



print('API Call 종료 : {}시{}분{}초- 경과시간 : {}'.format(time.localtime().tm_hour, time.localtime().tm_min,
                                                  time.localtime().tm_sec, time.time() - start))

df_result.to_csv("저장 위치를 적으시오.", mode='w', encoding="utf-8-sig")
print("엑셀 파일 OK")